apiVersion: v1
kind: Service
metadata:
  name: bgnodeapp-service
  labels:
    app: bgnodeapp
spec:
  type: NodePort
  ports:
   - protocol: TCP
     port: 8888
     nodePort: 30050
  selector:
    name: nodeapp
    version: "ENV_NAME"
