apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: nodeapp-blue
spec:
  destination:
    name: bg-internal-istio
  precedence: 1
  route:
  - labels:
      version: "VERSION"
    weight: 100

